services:
  db:
    image: postgres:17
    container_name: cafeteria_db
    restart: always
    environment:
      POSTGRES_DB: tienda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro

  api:
    build: .
    container_name: cafeteria_api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data: